### ISSUE TITLE
Implement 1.19.2 chat signing 

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#1046]
![chat_signin](https://user-images.githubusercontent.com/2346494/204388134-751b1dc5-a2be-4db0-98ac-6ba7f816ed48.jpg)

From @Kashalls

**Comment by rom1504** [comment]
<https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/ClientPacketListener.java#L2308-L2309> ServerboundChatAckPacket sent from client -> server every 64 messages they recieve ; server can then process the ACKs and kick client ...<https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/server/network/ServerGamePacketListenerImpl.java#L1454> for reasons in enum at <https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/network/chat/LastSeenMessagesValidator.java#L128>

From @extremeheat

**Comment by rom1504** [comment]
https://youtu.be/wn6fBvW4WOg?t=100 relevant video

**Comment by rom1504** [comment]
High level:
* Keep N last messages
* use that to produce a signature to send message
* expose that as a function in NMP
* use in examples and in mineflayer

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-auth/pull/65/files related

**Comment by rom1504** [comment]
ideas to go forward here:
* dig into mc java code
* use https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/examples/proxy to get some examples of chat packet
* help define the right API

**Comment by rom1504** [comment]
More ideas:
* Check if anyone else implemented it and do the same

**Comment by rom1504** [comment]
https://github.com/adepierre/Botcraft/blob/master/botcraft/src/Network/NetworkManager.cpp#L172-L206

https://github.com/adepierre/Botcraft/blob/master/botcraft/src/Network/Authentifier.cpp#L288

From https://github.com/adepierre/Botcraft/issues/102#issuecomment-1340159326

**Comment by extremeheat** [comment]
Some links to the minecraft java source for clientbound chat handling, not including verification :

* When a player message packet is received by the client, this handler is run in ClientPacketListener: https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/ClientPacketListener.java#L768 (if the message type doesn't exist in the dimension codec sent in the [login packet](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.19/loginPacket.json#L15), then the message is dropped as the client can't format it)
* If the message is valid, runs `handleChatMessage()` in nmc.multiplayer.chat.ChatListener https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L160
  * if a received client chat message has a [profileId of NULL](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/network/chat/MessageSigner.java#L39) in the ClientboundPlayerChatPacket packet, it's [read as a system message](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L107)
  * handleMessage is a throttle (maybe to prevent chat flooding lag?), otherwise accept() is called immediately
  * if ClientboundDeleteChatPacket is sent by the server, [chat message is removed](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/ClientPacketListener.java#L786) and [`removeIfSignatureMatches`](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L123) is called in ChatListener to handle the case that a message is removed while in the throttle queue -- if this happens, [the header is processed then pushed to chat history](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L116) and the message will be removed from the queue before it's shown to user. If the message was already shown, it's just removed from the GUI
* after an clientbound message is accept()'ed, in processPlayerChatMessage [it's verified](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L171)
* it's then [pushed to the chat reporting log](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L192) 
* after that it's pushed to the recent message queue, the [smaller non-reporting one](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/chat/ChatListener.java#L164) -- [only 5 messages wide](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/ClientPacketListener.java#L327)
  * every 64 messages the [client should send an acknowledgements to the server](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/client/multiplayer/ClientPacketListener.java#L2309) -- to which the server will [process and kick](https://github.dev/extremeheat/extracted_minecraft_data/blob/client1.19.1/client/net/minecraft/server/network/ServerGamePacketListenerImpl.java#L1456) if there is desync

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-auth/pull/65  for the reporting payload which is similar to what nmp will need to store in memory

from extremeheat

**Comment by rom1504** [comment]
This issue is funded at $150

**Comment by rom1504** [comment]
Thanks @frej4189 and @extremeheat for solving this one!

As agreed with extremeheat, granting the $150 to @frej4189

**Comment by rom1504** [comment]
relevant PRs
https://github.com/PrismarineJS/node-minecraft-protocol/pull/1049
https://github.com/PrismarineJS/node-minecraft-protocol/pull/1052
https://github.com/PrismarineJS/node-minecraft-protocol/pull/1050
