### ISSUE TITLE
Ping is not a recognized export

### ISSUE THREAD

**Issue by Opisek** [PrismarineJS/node-minecraft-protocol#1253]
[ x ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.44.0
 - server: irrelevant
 - node: 18.16.1

## Detailed description of a problem
The ``ping`` function is not recognized by node as an export. Everything else I've used worked fine.

In more detail:
```js
import { ping } from "minecraft-protocol";
```
Produces the error
```
import { ping } from "minecraft-protocol";
         ^^^^
SyntaxError: Named export 'ping' not found. The requested module 'minecraft-protocol' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'minecraft-protocol';
const { ping } = pkg;
```

The only way I found I could overcome this is by using
```js
import * as minecraftProtocol from "minecraft-protocol";
// ...
minecraftProtocol.default.ping(/* ... */);
```

## Current code
```js
import { ping } from "minecraft-protocol";
```

## Expected behavior
``ping`` should be a recognized export

**Comment by Opisek** [comment]
Alright, I see. I created this issue, because I could import everything else the ESM way with no issues, so ``ping`` was the outlier to me.

**Comment by extremeheat** [comment]
The import syntax [does not do destructuring](https://qntm.org/snippets), despite the similar syntax. It instead looks up objects against the module's ESM exports list. The technical reason for this is that ESM export/import lookups are done statically in the parse step before the program is run. This is so browsers can asynchronously load all the dependencies for a page without needing to synchronously run the code and fetch the deps one by one. With CommonJS only an object is exported (or a function/variable under the module.export variable), that's translated to the `default` export in ESM. Now setting aside CommonJS translation, the `default` export in ESM is intended for when you want to export an anonymous function or variable from a file, which would be named by the caller. Like the error message says you would need to use a different import syntax for destructuring:

```js
import pkg from 'minecraft-protocol'; // pkg gets the default export variable and assigns it to pkg
const { ping } = pkg; // this actually does destructuring to get the ping function from pkg object
```

When you do a "[namespace import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#forms_of_import_declarations)" like:
```js
import * as pkg from 'pkg'
```
You are binding all the ESM exports into pkg, including the `default` one.


So why can you do `import {x, y, z} from 'pkg'` or `import * as pkg from 'pkg'; pkg.x` sometimes as opposed to using the default object in Node.js? That's because Node.js added a compatibility feature to try and export all the CommonJS exports as ESM exports. But again since all the ESM import/export are done statically, that compatibility feature works without running the code. So it can only use static analysis to try and make the CommonJS module look like an ESM one before the code is ran. You can see this for yourself by adding a console.log to the top of node_modules/minecraft-protocol/index.js and checking that error on importing ping -- no log will be made. If the static translator gets stuck, it will give up trying to promote things inside module.export to ESM exports, so you must use the default export object and destructure at runtime.

**Comment by Opisek** [comment]
I see. Thank you for the comprehensive explanation and apologies for my confusion!
