### ISSUE TITLE
Chunk size is 23 but only 15 was read ; partial packet : {"name":"entity_sound_effect","params":{"soundId":526,"soundCategory":2,"entityId":52724,"volume":16,"pitch":1}}; buffer :5c8e0402f49b03418000003f800000fb8f631a089c6c66

### ISSUE THREAD

**Issue by DarkCoder15** [PrismarineJS/node-minecraft-protocol#1255]
[v] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: ^1.44.0
 - server: vanilla/spigot/paper Paper 1.19
 - node: 20.5.0

## Detailed description of a problem
Some packets cause crash, like this one:
```
Chunk size is 23 but only 15 was read ; partial packet : {"name":"entity_sound_effect","params":{"soundId":526,"soundCategory":2,"entityId":52724,"volume":16,"pitch":1}}; buffer :5c8e0402f49b03418000003f800000fb8f631a089c6c66
```

## Expected behavior
Packet should go through proxy

**Comment by vincss** [comment]
Hi,
I encountered the same error, when someone is trying to connect, it returns an error to the client even if the setting "hideErrors: true" .
It would be nice if it returns a proper message to the client.
![image](https://github.com/PrismarineJS/node-minecraft-protocol/assets/2254806/ed0fdc8d-9bba-4e58-a681-cbf76c32760d)

@rom1504

**Comment by extremeheat** [comment]
Looks like caused by incorrect change in https://github.com/PrismarineJS/minecraft-data/pull/731.

[Sound Packet](https://github.com/extremeheat/extracted_minecraft_data/blob/client1.19.3/client/net/minecraft/network/protocol/game/ClientboundSoundPacket.java) and [Entity Sound Packet](https://github.com/extremeheat/extracted_minecraft_data/blob/client1.19.3/client/net/minecraft/network/protocol/game/ClientboundSoundEntityPacket.java) don't have any switch statement, it's id (varint), enum (varint) and other float and integer fields. Not sure where that data is coming from

**Comment by rom1504** [comment]
fixed

**Comment by vincss** [comment]
Hi ,
Thanks for the update.
There seems to be an issue with some characters since the latest update : 
![image](https://github.com/PrismarineJS/node-minecraft-protocol/assets/2254806/fc3e51e8-fc73-4d77-b68c-d7681a1718ea)

**Comment by rom1504** [comment]
@vincss what are you running? Mineflayer is not supported yet

**Comment by vincss** [comment]
Hi,
On the server side it is
https://github.com/vincss/mcsleepingserverstarter/
And the client is the regular one.

**Comment by rom1504** [comment]
What packets are you using? Multiple packets changed in 1.20.2

**Comment by vincss** [comment]
I updated :   "minecraft-protocol": "^1.45.0"
which updated the others packages in package-lock.json
https://github.com/vincss/mcsleepingserverstarter/commit/06be9ce1c5cfc445d3bf0ce5ddb23496ef109491
