### ISSUE TITLE
Setup and using?

### ISSUE THREAD

**Issue by ReduxRedstone** [PrismarineJS/node-minecraft-protocol#191]
Hello, this isnt really a bug or anything but I have no idea how to use node-minecraft-protocol or Mineflayer or anything like that on my vanilla test server. Ive used things like rcon before but all i had to do was set an rcon password in my server config and connect via my ip, port and password but these want emails and stuff, im very confused. I emailed Andrew Kelley about how this issue and he told me "Hello, please file an issue on GitHub. This way other people can participate in the discussion." which is what im doing.  Ive also got a few questions about the systems in general but he told me to make this post so i guess ill ask them here in and hope for some answers. Firstly, whats the highest version these will work for? It says it supports version 1.8.1 but is that the highest version supported? If not, how do i make it work for higher versions? And also, are these even meant to be used on vanilla? I watched Andrews videos from around a year or two ago about Mineflayer and I feel like its not meant for vanilla, but there wasnt any ifo provided about that. Sorry if this isnt where I should post this, im just doing what Andrew told me to do. If theres a better place to post this then ill gladly post it there instead.

**Comment by wtfaremyinitials** [comment]
@ReduxRedstone The reason this project an email address and password is because it's logging in to a Minecraft client, not connecting to an RCON server. (If you want to connect to RCON, check out [pushrax/node-rcon](https://github.com/pushrax/node-rcon))

This currently works with 1.8.7.

We try to keep this repo up to date with each new release (the lack of snapshots haven't helped with the upcoming 1.9 though), but if you'd like to help updating, we'd definitely appreciate it.

Yes, it works best in Vanilla in fact. Bukkit and Spigot are also supported.

**Comment by ReduxRedstone** [comment]
alright, thats good to know. im still not %100 sure about how to set it all up though. the comments of an issue report probably arent the best, or most wanted, place to deal with a node newb like me so would you mind emailing me some instruction on how all this works? my email is halolink44@gmail.com

**Comment by wtfaremyinitials** [comment]
I'm happy to email you in a few days, I'm unfortunately up to my eyeballs in work right now. If you'd like to chat with everyone else involved in the project, I'd recommend checking out our gitter chat channel [here](https://gitter.im/PrismarineJS/node-minecraft-protocol).

**Comment by ReduxRedstone** [comment]
alright, thank you. ill do that

**Comment by rom1504** [comment]
I think we can close this issue ?
