### ISSUE TITLE
Cross version

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#234]
There are 2 kinds of cross version support:
- static : for one instance of a program using nmp, only one version is supported
- dynamic : for one instance of a program using nmp, several versions are supported

Currently we almost got static support (see #212 about that).

You'd think dynamic support would be much harder but actually all it would be about is getting the protocol information from the server/client you are connecting to, and using the correct protocol.json to parse and serialize the packets for that server/client.

Of course, that wouldn't solve the multi-version support for users of nmp which would still have to deal with the packets difference between version, one way to deal with that might be #231 

Dynamic support  would allow createClient and createServer to work for both 1.8 and 1.9 without   change to the api, nmp would just need to expose the version of the server/client  it connected to.

This idea might be extendable to multi-platform support (with mcpe) but that would be a bit harder (the protocol architecture of mcpe is different from mcpc)

Related with #65

**Comment by rom1504** [comment]
About dynamic support:
Adding a versions:["1.8", "1.9"] option to createClient so that 
 the bot will only connect to versions supported by the nmp user.

And the default versions might be just ["1.8"] in nmp 0.15.0 . In 0.16.0 it might become ["1.9"] and the nmp user would anyway would have to manually update to 0.16.0 so we wouldn't "pull the rug under the user's feets".

Or we could just say that "versions" is not optional.

Dynamic just mean multiple versions support at the same time, we don't force the user to support everything if he doesn't care to.

(the same thing goes for createServer)

**Comment by rom1504** [comment]
We need to be able to convert the protocolVersion (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L143) (=version.version) to the corresponding majorVersion/mcDataVersion. node-minecraft-data should be able to do that in https://github.com/PrismarineJS/node-minecraft-data/blob/master/index.js#L18 (just check if one of the mcData submodule is that version)

Then we basically just need to do `require('minecraft-data')` when we know the version. To have cross version support dynamically I think we'd need to assume the other states than play are the same cross version (is this true ?) in order to go far enough for the client/server to give us the version he wants.

**Comment by roblabla** [comment]
@rom1504 it would work for anything >= 1.7. For < 1.6, there would only be one state (LEGACY, or whatever we end up calling it). I think we should keep the require('minecraft-data')('version'). It's easier and more flexible.

**Comment by rom1504** [comment]
Ah yeah sure, I forgot the version. I meant putting require ('minecraft-data')(protocolVersion) when the client (or server) sends us the protocol version

**Comment by rom1504** [comment]
Places that should use a dynamically stored version : 
* createServer.js [ping](https://github.com/PrismarineJS/node-minecraft-protocol/blob/4a1b2bf052958dcb579a52707b80c882b3d478eb/src/createServer.js#L90] and [set_protocol](https://github.com/PrismarineJS/node-minecraft-protocol/blob/4a1b2bf052958dcb579a52707b80c882b3d478eb/src/createServer.js#L143)
* ping.js [set_protocol](https://github.com/PrismarineJS/node-minecraft-protocol/blob/4a1b2bf052958dcb579a52707b80c882b3d478eb/src/ping.js#L35)
* createClient.js [set_protocol](https://github.com/PrismarineJS/node-minecraft-protocol/blob/4a1b2bf052958dcb579a52707b80c882b3d478eb/src/createClient.js#L79) 
* client.js [packets loading](https://github.com/PrismarineJS/node-minecraft-protocol/blob/e3b435af1b4a3fad192d9534fca2cac466c520eb/src/client.js#L11)
* serializer.js [packets loading](https://github.com/PrismarineJS/node-minecraft-protocol/blob/74e4d415fbd8299eb27cf5e970aac35e8a11f52a/src/transforms/serializer.js#L50)
* test.js [version checking](https://github.com/PrismarineJS/node-minecraft-protocol/blob/a2abb70fc7427a34cfed511555e0244fc42e8ef8/test/test.js#L455) 
* circle-ci [server download](https://github.com/PrismarineJS/node-minecraft-protocol/blob/a2abb70fc7427a34cfed511555e0244fc42e8ef8/circle.yml#L11)
* index.js [packets exposing](https://github.com/PrismarineJS/node-minecraft-protocol/blob/e3b435af1b4a3fad192d9534fca2cac466c520eb/src/index.js#L7)
* browser.js [packets exposing](https://github.com/PrismarineJS/node-minecraft-protocol/blob/e3b435af1b4a3fad192d9534fca2cac466c520eb/src/browser.js#L2)

**Comment by rom1504** [comment]
I think I'll start by implementing static cross version (the API proposed in #65) before dynamic, it's easier.

**Comment by rom1504** [comment]
Once #257 is merged, adding dynamic cross version will mainly be about changing the serializer and deserializer dynamically in client.js when we know the version we want.

**Comment by rom1504** [comment]
hmm hmm, so it seems the server never send the version to the client, so it doesn't seem possible to implement dynamic cross version for the client.

**Comment by rom1504** [comment]
Once dynamic cross version implemented, I think a good API for createClient and createServer would be:

* no version option is provided : default to enabledVersions = [defaultVersion]
* version:"1.9" : enabledVersions = ["1.9"]
* version:["1.8","1.9"] : enabledVersions = ["1.8","1.9"]
* version:"any" : enabledVersions = supportedVersions

Then NMP would refuse to connect to any version not in enabledVersions.

**Comment by deathcap** [comment]
> Ah actually, the client can ask the server its version with the ping packet, and get it back with the pong packet

Implemented exactly this in https://github.com/PrismarineJS/node-minecraft-protocol/issues/327 :). It works pretty well in my testing, though as @roblabla mentions the ping exchange adds additional latency to the connection time and incompatibility with servers that do not allow ping, so it is probably a good idea to make it optional. The client also has to wait for the ping response from the server before it creates the client and sets a version, so the current synchronous `client = createClient()` API is troublesome.

How about keeping createClient() as is — only accepting one version — but add a wrapper for dynamic cross protocol support? (this is what I'm doing in node-minecraft-protocol-auto in #327). This way, existing clients won't break nor get the ping overhead, and the API signature can change (createClient is sync, but this new ?createClientAsync? API could be async, accepting a callback function to return the client object once it is created).

Maybe FML/Forge (https://github.com/PrismarineJS/node-minecraft-protocol/pull/326) could also be considered as "version" for the cross-version support? Not in the same enabledVersions list, but a separate boolean option. idk if we actually need enabledVersions, if the current API remains for specifying exactly one version, and there is another API for automatically getting and using the appropriate version, unless filtering the supported versions is desired for some reason.

**Comment by deathcap** [comment]
In https://github.com/PrismarineJS/node-minecraft-protocol/pull/331 (ready to pull/review), left the default `version` option to `createClient()` as it is (defaults to 1.8 currently), but now also allow `version: false` to enable the autoVersion() client plugin.

This works alright but there are some larger worthwhile improvements imho. These may require changes to multiple projects.

**Naming consistency**: the term `version` is variously in the code used to refer to the version object, the major version (`version` parameter to createClient), the release version, and the protocol version (as in `version.version`). It would be clearer if the protocol version number code (47) was always `protocolVersion`, and maybe version objects (from minecraft-data) as `versionInfo` or something. 

**Major version / dataset dichotomy**: [minecraft-data](https://github.com/PrismarineJS/minecraft-data/tree/master/data) is built around one set of data per major version. Not necessarily an unreasonable assumption, but it breaks down when considering protocols. The 1.7 major version encompasses both protocol version 4 (1.7.1 to 1.7.5) and 5 (1.7.6 to 1.7.10) for example, and 1.9 (prerelease) just had a recent major protocol change making 15w40b (76) in minecraft-data/1.9 incompatible with newer 1.9 prereleases (renumbering the packets). I think we can tackle this problem by abstracting out the "dataset" from the "version", so for example, you would ask minecraft-data "give me the protocol for version X" (where X = 76, or '15w40b', etc.,), and it would return the appropriate set of data, if available. The data could be stored in 1.8/, 1.7/ directories internally, but not exposed to users of the module.

**Major versioning in createClient/client object**: the constructor takes a majorVersion as the second argument, should be changed to use the release version, and let minecraft-data handle getting the right data. This might already be possible in minecraft-data 0.16.0 since it supports `require('minecraft-data')('15w40b')` for example, but should be explicit in node-minecraft-protocol, and the createClient() factory method should use the version from the versions object array, instead of `mcData.version` (which probably could be removed? since version:data is a n:n mapping)

**Remove version in constructors?**: I suppose it makes sense for the Server object, but for Client, we want to be able to create the object and return it without immediately knowing its version. Currently, the version is set, and then overridden after the object is created.

**Version validation**: src/createClient.js validates the supported version, but it is not validated when set afterwards (`client.version = majorVersion; client.state = states.HANDSHAKE`). It is partially validated in that the version must be known to minecraft-data protocolVersions, but not that there is any protocol data available for it. Maybe make version property with a setter to validate, and also have it setup the serializers for the right version when set.

**Comment by rom1504** [comment]
Client cross-version is now implemented (thanks @deathcap)
Missing here is at least server cross-version. That requires less change since we already get the version from the client there https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L187

**Comment by deathcap** [comment]
Found this protocol recognizer in Cuberite, might be useful for reference: https://github.com/cuberite/cuberite/blob/master/src/Protocol/ProtocolRecognizer.cpp#L948

**Comment by rom1504** [comment]
@kobiluvesmemes is interested by dynamic cross version in the server. I might do it.
and modularize the server in the process (related https://github.com/PrismarineJS/node-minecraft-protocol/pull/210)

**Comment by kobiluvesmemes** [comment]
How long until this is on npm?

**Comment by rom1504** [comment]
@kobiluvesmemes released as 1.4.0
