### ISSUE TITLE
Increase the major version ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#361]
It is advised not to use the <1.0.0 version these days, because they have weird semver rules.
Maybe we should release a 1.0.0 next time we change some stuff.

**Comment by deathcap** [comment]
:+1: was also about to suggest this; semver 0.x.y effectively loses the "patch" version and makes the minor the major.

If this module was bumped to x.y.z then it could effectively use all of the versioning (major/minor/patch). For example https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/HISTORY.md#0160 "breaking change" would instead (or additionally) be denoted by bumping the major version, and backwards-compatible enhancements (such as adding new protocols, at least if it was possible in a backwards-compatible manner, especially with older protocol versions) by bumping the minor version (and bugfixes by bumping the patch version).

**Comment by roblabla** [comment]
I never bumped to 1.x because it's pretty hard to maintain compatibility when you're bound to the minecraft version.

Now that NMP isn't bound to a minecraft version, breaking changes should happen much more rarely. Although changing the default version is a breaking change, so we might want to either force people to specify the version, or not change the default ever.

The idea is that code I wrote a gazillion years ago should still work with almost no work on a newer version of NMP (given the server didn't change version). Being in 0.x.y tells people "hey, this API changes a LOT". If we can commit to API stability, then bumping to 1.0 is OK.

**Comment by rom1504** [comment]
done
