### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by mcparadip** [PrismarineJS/node-minecraft-protocol#479]
When I try to connect to a server using client_auto.js, it gives me "Killed." and disconnects.

Why is this happening?

**Comment by rom1504** [comment]
Which server

**Comment by mcparadip** [comment]
Many servers, most of them

**Comment by roblabla** [comment]
You'll have to give us a whole lot more of information. What operating system ? What nodejs version ? What minecraft version of the server ? 

Usually, "Killed." on linux means that your machine ran out of memory, and the kernel killed some software (more or less at random) to reclaim it. I say "usually" though because that's not the only case in which it'll happen.

**Comment by mcparadip** [comment]
Linux, node v6.9.4, Minecraft 1.9.4

**Comment by mcparadip** [comment]
try connecting to `cypruspvp.nitrous.it`

**Comment by rom1504** [comment]
Just tried it. It works here (node 6.5)

**Comment by rom1504** [comment]
Can you paste the complete output ?

**Comment by mcparadip** [comment]
It connects for a few seconds, then just says "Killed." and exits.

**Comment by rom1504** [comment]
Do you have any ram left ?

**Comment by mcparadip** [comment]
I don't know, I'm trying on a web service.

I'll try it on my computer when I get home.

**Comment by rom1504** [comment]
Did you find the problem ?

**Comment by mcparadip** [comment]
Yes.
