### ISSUE TITLE
Proxy.js Online Mode

### ISSUE THREAD

**Issue by bluestreek18** [PrismarineJS/node-minecraft-protocol#494]
Does the proxy example to work with online mode?

I have set online mode to true in proxy.js file and I get:
`[12:17:23] [User Authenticator #2/INFO]: Disconnecting /127.0.0.1:54048: Failed to verify username!
[12:17:23] [User Authenticator #2/ERROR]: Username 'username' tried to join with an invalid session`

I am connecting to the proxy from a vanilla mc client. If I set offline mode to true in my server.properties everything connects fine.

Thanks

**Comment by rom1504** [comment]
There are 2 online mode settings in a proxy : client side and server side.
Minecraft security model make it impossible to set both to online mode : otherwise you could do man in the middle attacks.
But you can indeed set either the client side or the server side to online mode.
If you set the client side to online mode, then the proxy will be in charge of the auth of clients.
If you set the server side to online mode, then you need to put your credentials directly in the proxy code.

**Comment by rom1504** [comment]
if you have any other question, feel free to ask
