### ISSUE TITLE
NMP Required Changes

### ISSUE THREAD

**Issue by ShayBox** [PrismarineJS/node-minecraft-protocol#558]
- [x] Add coding standard
- [x] Switch callbacks to promises/async/await, Node v8 is LTS now guys, callbacks were replaced.
- [x] Start using JSDoc because the docs suck.
- [x] Fix any objects that use strings as keys, Ex. 'max-players' and 'online-mode' (Part of coding standard)

**Comment by rom1504** [comment]
1) yes standardjs can be setup if you feel that's necessary
2) where do we use callbacks ?
3) no jsdoc is a bad idea, out of code documentation is better. If you see
something missing, it can be added.
4) so all the js code ever written then ? Js is mostly objet mapping keys
(strings) to value. Yes "maxPlayer" is a string.
Not sure what's the benefit to switching to maxPlayer but why not. (It is
currently called max-player because the option is called that in the
minecraft server options)

**Comment by rom1504** [comment]
done
