### ISSUE TITLE
Allow for customizing the online players

### ISSUE THREAD

**Issue by ShayBox** [PrismarineJS/node-minecraft-protocol#565]
In createServer I see there's an onlinePlayers var, but it's set to 0 rather than letting you set it in options, useful for a proxy to represent the server's players

**Comment by rom1504** [comment]
Hi,
I can't see any onlinePlayers var.
The only thing we set to 0 is `playerCount` because that's its initial value (it is then incremented there https://github.com/PrismarineJS/node-minecraft-protocol/blob/db1cbd49411225a355eb41f953cfa9963505ae06/src/server/login.js#L120 )
What are you trying to do ?

This is js so you can add anything you want in your code in the server or client object.
Though I recommand you to have another object to store you stuff like we do in mineflayer and flying-squid. (our exact pattern is `bot._client` or `player._client`)

**Comment by ShayBox** [comment]
Closing old issues

**Comment by rom1504** [comment]
It's closed because it's invalid (there's nothing to fix) not because it's old. We don't close old issues that still need fixing.
