### ISSUE TITLE
@xboxreplay/xboxlive-auth - Upcoming 4.0.0 release

### ISSUE THREAD

**Issue by Alexis-Bize** [PrismarineJS/node-minecraft-protocol#807]
Hey there, first of all, thanks for using `@xboxreplay/xboxlive-auth` library.

In the upcoming days, a new major version will be released which includes a few of breaking changes and new features / workarounds such as "deviceToken" generation, "Child" / "Teen" account detections, Electron usage, etc.

Please refer to the available documentation right here: https://github.com/XboxReplay/xboxlive-auth/tree/4.0.0/docs

Thank you!

Update: The `4.0.0-beta.0` is available on npm - https://www.npmjs.com/package/@xboxreplay/xboxlive-auth/v/4.0.0-beta.0

**Comment by rom1504** [comment]
@extremeheat can you have a look ? Does it make sense relative to your open
PR ?

**Comment by extremeheat** [comment]
Thanks for working on this @Alexis-Bize, didn't know you were working on it. I wasn't aware that device token and device code were two different things. As a command line program, possibly needing to be run on remote/cloud servers, we had some constraints:

* needs to able to work headless (we cannot easily open a window if running over ssh for example)
* needs to be refreshable to minimize the need to re-authenticate (helps for automation)
* needs to work when we cannot easily open a webserver due to firewalls and other rules
* needs to be relatively stable

I wasn't sure if all those points could be checked off together, username+password kind of works, but there's just too many scenarios where this wouldn't work without user input even ignoring 2FA, plus the added security concerns particularly being Minecraft. 

@azure/msal-node does give an official way to do the ms auth part, maybe you can look into using that. The only problem I had with it is that there's no easy way to refresh tokens without patching the library or reading into the cache (see https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2836). Apparently the library deals with refreshing itself, but I couldn't get it to work so in #806 I take the tokens out of their cache and validate it ourselves.

Doing a redirect URL causes problems with point 3, so can you look into adding device code auth?  Maybe some of #806 could be helpful to merge into XBL-auth so it can be used for other projects too, can give your opinion on that?

The other stuff you added with xbox api could be helpful, but I'm a bit confused with the child/teen accounts, is there a way to make these work too or is your update just there to detect them?

**Comment by Alexis-Bize** [comment]
### Remote / cloud servers constraints

Those constraints are difficult to bypass. Perhaps there's a possible workaround where the user do not set its credentials (email / password) but the returned live tokens instead. As 2FA can be an issue during the initial authentication, maybe you should use an Electron application ([see example](https://github.com/XboxReplay/xboxlive-auth/tree/4.0.0/examples/electron-app)) for this part. 

* The user authenticate itself via the login.live.com prompt (Electron).
* The application catch returned access_token / refresh_token / etc.
* The application display them to the user.
* The user use them inside your library.
* The library must handle the refresh part (see [live.refreshAcessToken](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/docs/05-Methods.md#method-refreshaccesstoken)

```javascript
import { xbl, live } from '@xboxreplay/xboxlive-auth';

// Specified by the user itself / returned by the library
let rpsTicket = 'USER_RPS_TICKET';
let refreshToken = 'USER_REFRESH_TOKEN';

const XBLAuthenticate = async (retry = false) => {
	const exchange = await xbl
		.exchangeRpsTicketForUserToken(rpsTicket, 't') // Use "d" for custom Azure applications
		.catch(err => {
			if (retry === true || err.details.statusCode !== 401) {
				throw new Error('Authentication has failed');
			}

			// Current "RpsTicket" has expired
			return live
				.refreshAccessToken(refreshToken) // Specify "clientId", "scope", etc. for custom Azure applications
				.then(refreshTokenResponse => {
					rpsTicket = refreshTokenResponse.access_token;
					refreshToken = refreshTokenResponse.refresh_token;
					return XBLAuthenticate(true);
				});
		});

	const {
		Token: deviceToken
	} = await xbl.EXPERIMENTAL_createDummyWin32DeviceToken();

	const XSTSTokenResponse = await xbl.exchangeTokensForXSTSToken({
		XSTSRelyingParty: 'rp://api.minecraftservices.com/',
		userTokens: [exchange.Token],
		deviceToken: Token // Used to bypass "Child" and "Teen" accounts restriction
	});

	return XSTSTokenResponse;
};
```

**Comment by extremeheat** [comment]
Yes, right now in #806 we have msa device code based authentication. The server sends us a code, url, and a message for the user. We send that message back to the user to have them follow the instructions sent by the server, then the ms auth library (msal) constantly polls to check the status of the authentication. If it’s successful, the promise resolves and we continue with the auth flow onto the Xbox step with your library to get the final XSTS data, onto the Minecraft step. We store the tokens so this step doesn’t have to be repeated. Sending username and password works some of the time without user interaction, but not all the time, and would be a maintenance chore every time Microsoft changes something with their auth page and it’s hard to debug other people’s issues if we can’t reproduce. So we need to have an alternative. 

Regarding adding the new auth flow in your library:

As this is also a library, usually used in headless environments, there’s a lot of different environments we have to account for. Bundling electron is not a good idea for the library, it would add 100 MB+ to the package size and would only work if the users are in a GUI environment. 

So for the library side to support the auth_code flow, we’d need to start a server, or delegate the auth step to the user. We do have a example using the library in an electron app, this is where I think the authorization_code flow would be helpful: we can get the live url the user needs to go to, send it to the user in a callback, user code starts up a electron window with the login page and sends the the relevant data back like in your example so we can continue the auth flow. (Currently with device_code auth we just alert the user the code and wait for them deal with it.)

It’s a bit complicated to explain, but it comes down to:

* email and password based auth - (no GUI, sometimes user interaction) xboxlive library handles
* device code auth - (no GUI, requires user interaction) msal library handles, we give user code, we wait for user complete the auth there 
* authorization code - (new, requires GUI, requires user interaction) xboxlive library gives us a url, nmp sends it back to the user in a callback, have them send us back the access/refresh token 

I’ll look at updating the #806 PR to use 4.0 soon, but can you answer the questions in my  comment above ? Thanks

**Comment by Alexis-Bize** [comment]
The main issue with auth_code flows (device / authorization) is that they block the authentication process as it requires user input. Credentials authentication may requires extra steps (authorize an unknown location authentication, 2FA, etc.), so the idea behind an Electron app is to let the user to retrieve and use its `refresh_token` instead. The app should not be added the library but you could give a link to download it for each architecture.

As I want to keep `xboxlive-auth` module as headless / simple as possible, I have no plan to add extra libraries that may block the authentication itself.

Note: Latest beta `4.0.0-beta.1` includes the [authenticateWithUserRefreshToken](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/docs/01-Authenticate.md#method-authenticatewithuserrefreshtoken) method.

Feel free to ping me on Discord (Zeny#7777) if you want to discuss about possible workarounds or have additional info about Live / XBL auth flows to make it work for you.
